/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.sheltermonitoring;

import business.EcoSystem;
import business.useraccount.UserAccount;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import ui.uiutils.UiUtils;

/**
 *
 * @author Geetha
 */
public class HomelessIndividualJPanel extends javax.swing.JPanel {

    private final JPanel container;
    private final UserAccount account;
    private final EcoSystem system;

    /**
     * Creates new form HomelessIndividual
     */
    public HomelessIndividualJPanel(JPanel container, UserAccount account, EcoSystem system) {
        initComponents();
        this.container = container;
        this.account = account;
        this.system = system;
        
        titleLabel.setText("Welcome, " + account.getIndividual().getName());
        
        imgthree.setIcon(new ImageIcon(new ImageIcon("images/homelesswelcome.png").getImage(
                ).getScaledInstance(250, 250, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enrollButton = new javax.swing.JButton();
        docButton = new javax.swing.JButton();
        maintenanceButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        imgthree = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        enrollButton.setBackground(new java.awt.Color(38, 55, 85));
        enrollButton.setForeground(new java.awt.Color(255, 255, 204));
        enrollButton.setText("Enroll in Training Course");
        enrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollButtonActionPerformed(evt);
            }
        });

        docButton.setBackground(new java.awt.Color(38, 55, 85));
        docButton.setForeground(new java.awt.Color(255, 255, 204));
        docButton.setText("Request Doctor Appointment");
        docButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docButtonActionPerformed(evt);
            }
        });

        maintenanceButton.setBackground(new java.awt.Color(38, 55, 85));
        maintenanceButton.setForeground(new java.awt.Color(255, 255, 204));
        maintenanceButton.setText("Request House Maintenance");
        maintenanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maintenanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgthree)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(37, 37, 37)
                .addComponent(docButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maintenanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enrollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imgthree)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceButtonActionPerformed
        // TODO add your handling code here:
        UiUtils.nextScreen(container, 
            new RequestMaintenanceJPanel(container, account, system), 
            "RequestMaintenanceJPanel");
    }//GEN-LAST:event_maintenanceButtonActionPerformed

    private void enrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollButtonActionPerformed
        // TODO add your handling code here:
        UiUtils.nextScreen(container, 
            new CourseEnrollmentJPanel(container, system, account), 
            "CourseEnrollmentJPanel");
    }//GEN-LAST:event_enrollButtonActionPerformed

    private void docButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docButtonActionPerformed
        UiUtils.nextScreen(container, 
            new DoctorAppointmentJPanel(container, account, system), 
            "DoctorAppointmentJPanel");
    }//GEN-LAST:event_docButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton docButton;
    private javax.swing.JButton enrollButton;
    private javax.swing.JLabel imgthree;
    private javax.swing.JButton maintenanceButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
