/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.food;

import business.EcoSystem;
import business.useraccount.UserAccount;
import business.workqueue.FoodRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.uiutils.UiUtils;

/**
 *
 * 
 */
public class AcceptRejectOrders extends javax.swing.JPanel {

    private JPanel container;
    private EcoSystem system;
    private UserAccount account;
    private ArrayList<FoodRequest> reqList;
    private final List<UserAccount> chefList;

    /**
     * Creates new form AcceptRejectOrders
     */
    public AcceptRejectOrders(JPanel container, EcoSystem system, UserAccount account) {
        initComponents();
        this.container = container;
        this.system = system;
        this.account = account;
        this.reqList = system.getWorkRequestManager().getUnresolvedFoodRequests();
        
        showNewOrders();
        
        this.chefList = system.getFoodEnterprise().getAllChefs();
        chefCombo.removeAllItems();
        for (UserAccount c: chefList) {
            chefCombo.addItem(c.getIndividual().getName());
        }
    }

    private void showNewOrders() {
        ordersCBox.removeAllItems();
        int j = 1;
        for(int i=0; i < reqList.size(); i++) {
            FoodRequest wq = reqList.get(i);
            if (wq.getStatus().equals("SUBMITTED")) {
                ordersCBox.addItem("Order No. " + j + ". From : " + wq.getSender().getUsername());
                j++;
            }
        }
        
        orderDetailsText.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        ordersCBox = new javax.swing.JComboBox<>();
        acceptButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderDetailsText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chefCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Accept or Reject Orders");

        backButton.setBackground(new java.awt.Color(38, 55, 85));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 204));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        ordersCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersCBoxActionPerformed(evt);
            }
        });

        acceptButton.setBackground(new java.awt.Color(38, 55, 85));
        acceptButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(255, 255, 204));
        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        rejectButton.setBackground(new java.awt.Color(38, 55, 85));
        rejectButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rejectButton.setForeground(new java.awt.Color(255, 255, 204));
        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        orderDetailsText.setColumns(20);
        orderDetailsText.setRows(5);
        jScrollPane1.setViewportView(orderDetailsText);

        jLabel2.setText("Select Order -");

        jLabel3.setText("Select Chef to assign the order to -");

        jLabel4.setText("Order Summary -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(ordersCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(chefCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1))))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordersCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chefCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(rejectButton))
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        UiUtils.previousScreen(container, this);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ordersCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersCBoxActionPerformed
        int idx = ordersCBox.getSelectedIndex();
        if (idx < 0) 
            return;

        FoodRequest req = this.reqList.get(idx);
        orderDetailsText.setText(req.getMessage());
    }//GEN-LAST:event_ordersCBoxActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        int idx = ordersCBox.getSelectedIndex();
        if (idx < 0){
            JOptionPane.showMessageDialog(this, "Please select an order to accept.");
            return;
        }
        
        int chefIdx = chefCombo.getSelectedIndex();
        if (chefIdx < 0){
            JOptionPane.showMessageDialog(this, "Please select a chef to assign the order to.");
            return;
        }
        FoodRequest req = reqList.get(idx);
        req.setReceiver(chefList.get(chefIdx));
        req.setStatus("Accepted");
        system.getWorkRequestManager().updateWorkRequest(req);
        reqList.remove(idx);
        JOptionPane.showMessageDialog(this, "Order Accepted.");
        showNewOrders();
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        int idx = ordersCBox.getSelectedIndex();
        if (idx < 0){
            JOptionPane.showMessageDialog(this, "Please select an order to reject.");
            return;
        }
        reqList.get(idx).setStatus("Rejected");
        reqList.remove(idx);
        JOptionPane.showMessageDialog(this, "Order rejected.");
        showNewOrders();
    }//GEN-LAST:event_rejectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> chefCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea orderDetailsText;
    private javax.swing.JComboBox<String> ordersCBox;
    private javax.swing.JButton rejectButton;
    // End of variables declaration//GEN-END:variables
}
