/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.food;

import business.EcoSystem;
import business.useraccount.UserAccount;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import ui.uiutils.UiUtils;

/**
 *
 * @author Geetha
 */
public class FoodSupplyManagerJPanel extends javax.swing.JPanel {

    private final JPanel container;
    private final UserAccount account;
    private final EcoSystem system;
    
    /**
     * Creates new form FoodManagerJPanel
     */
    public FoodSupplyManagerJPanel(JPanel container, UserAccount account, EcoSystem system) {
        initComponents();
        
        this.container = container;
        this.account = account;
        this.system = system;
        
        titleText.setText("Welcome, " + account.getIndividual().getName());
        
        
        imgsevn.setIcon(new ImageIcon(new ImageIcon("images/orderfood.jpg").getImage(
                ).getScaledInstance(500, 400, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JLabel();
        ordersButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        imgsevn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        titleText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleText.setText("Welcome, ");

        ordersButton.setBackground(new java.awt.Color(38, 55, 85));
        ordersButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ordersButton.setForeground(new java.awt.Color(255, 255, 204));
        ordersButton.setText("Manage Orders");
        ordersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersButtonActionPerformed(evt);
            }
        });

        menuButton.setBackground(new java.awt.Color(38, 55, 85));
        menuButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 204));
        menuButton.setText("Manage Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ordersButton, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(imgsevn)))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleText)
                .addGap(39, 39, 39)
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(ordersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(imgsevn)
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        UiUtils.nextScreen(container, new ManageMenu(container, 
                account, system), "ManageMenu");
    }//GEN-LAST:event_menuButtonActionPerformed

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
        UiUtils.nextScreen(container, new AcceptRejectOrders(container, 
                system, account), "AcceptRejectOrders");
    }//GEN-LAST:event_ordersButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgsevn;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton ordersButton;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
